# .readthedocs.yaml
# Read the Docs configuration file
# Reference: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Simplified build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install your project and its dependencies
python:
  install:
    - requirements: docs/requirements.txt  # Path to the requirements file for the documentation
